//create alert table
CREATE OR REPLACE TABLE GOLD.BILLING_ALERTS AS
SELECT
    VISIT_ID,
    PATIENT_ID,
    DOCTOR_ID,
    TOTAL_CHARGES,
    VISIT_DATE,
    'HIGH BILLING ALERT' AS ALERT_TYPE
FROM GOLD.FACT_VISITS
WHERE TOTAL_CHARGES > 2000;




//automate alert
CREATE OR REPLACE TASK ALERT_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
AS

INSERT INTO GOLD.BILLING_ALERTS
SELECT
    VISIT_ID,
    PATIENT_ID,
    DOCTOR_ID,
    TOTAL_CHARGES,
    VISIT_DATE,
    'HIGH BILLING ALERT'
FROM GOLD.FACT_VISITS
WHERE TOTAL_CHARGES > 2000;


ALTER TASK ALERT_TASK RESUME;


//demo

INSERT INTO SILVER.PATIENT_VISITS (
    VISIT_ID,
    PATIENT_ID,
    DOCTOR_ID,
    DEPARTMENT_ID,
    VISIT_DATE,
    TOTAL_CHARGES
)
VALUES ('V4000','P001','D001','DEP01','2024-03-30',3500);

select * from silver.patient_visits;

EXECUTE TASK ALERT_TASK;

SELECT * FROM GOLD.BILLING_ALERTS;
