
USE DATABASE HOSPITAL_DB;
USE SCHEMA SILVER;


CREATE OR REPLACE STREAM VISIT_STREAM
ON TABLE SILVER.PATIENT_VISITS;

//TASK
CREATE OR REPLACE TASK LOAD_FACT_VISITS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('VISIT_STREAM')
AS

INSERT INTO GOLD.FACT_VISITS
SELECT 
    v.VISIT_ID,
    v.PATIENT_ID,
    v.DOCTOR_ID,
    v.DEPARTMENT_ID,
    v.VISIT_DATE,
    v.TOTAL_CHARGES,
    d.DIAGNOSIS,
    b.BILL_AMOUNT,
    p.PATIENT_NAME,
    doc.DOCTOR_NAME
FROM VISIT_STREAM v
LEFT JOIN SILVER.DIAGNOSIS d 
    ON TRIM(v.VISIT_ID) = TRIM(d.VISIT_ID)
LEFT JOIN SILVER.BILLING b 
    ON TRIM(v.VISIT_ID) = TRIM(b.VISIT_ID)
LEFT JOIN SILVER.DIM_PATIENT p 
    ON TRIM(v.PATIENT_ID) = TRIM(p.PATIENT_ID)
LEFT JOIN SILVER.DIM_DOCTOR doc 
    ON TRIM(v.DOCTOR_ID) = TRIM(doc.DOCTOR_ID);



ALTER TASK LOAD_FACT_VISITS RESUME;

show tasks;