
CREATE OR REPLACE TABLE BRONZE.PATIENT_VISITS_RAW ( 
    VISIT_ID STRING,
    PATIENT_ID STRING,
    DOCTOR_ID STRING,
    DEPARTMENT_ID STRING,
    VISIT_DATE STRING,
    CONSULTATION_FEE STRING,
    MEDICINE_COST STRING,
    LAB_COST STRING
);

COPY INTO BRONZE.PATIENT_VISITS_RAW
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8
    FROM @BRONZE_STAGE/PATIENT_VISITS_Hospital.csv
)
FILE_FORMAT = (TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1)
ON_ERROR = 'CONTINUE';




CREATE OR REPLACE TABLE BRONZE.DIAGNOSIS_RAW (
    VISIT_ID STRING,
    DIAGNOSIS STRING,
    SEVERITY STRING
);

COPY INTO BRONZE.DIAGNOSIS_RAW
FROM (
    SELECT $2, $3, $4
    FROM @BRONZE_STAGE/DIAGNOSIS_Hospital.csv
)
FILE_FORMAT = (TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1);




CREATE OR REPLACE TABLE BRONZE.BILLING_RAW (
    BILL_ID STRING,
    VISIT_ID STRING,
    BILL_AMOUNT STRING,
    BILL_DATE STRING
);

COPY INTO BRONZE.BILLING_RAW
FROM (
    SELECT $1, $2, $3, $4
    FROM @BRONZE_STAGE/BILLING_Hospital.csv
)
FILE_FORMAT = (TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1)
FORCE = TRUE;




CREATE OR REPLACE TABLE BRONZE.DIM_PATIENT_RAW (
    PATIENT_ID STRING,
    PATIENT_NAME STRING,
    CITY STRING
);

COPY INTO BRONZE.DIM_PATIENT_RAW
FROM (
    SELECT $1, $2, $3
    FROM @BRONZE_STAGE/DIM_PATIENT_Hospital.csv
)
FILE_FORMAT = (TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1)
ON_ERROR = 'CONTINUE';



CREATE OR REPLACE TABLE BRONZE.DIM_DOCTOR_RAW (
    DOCTOR_ID STRING,
    DOCTOR_NAME STRING,
    SPECIALIZATION STRING
);

COPY INTO BRONZE.DIM_DOCTOR_RAW
FROM (
    SELECT $1,$2,$3
    FROM @BRONZE_STAGE/DIM_DOCTOR_Hospital.csv
)
FILE_FORMAT = (TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1)
ON_ERROR = 'CONTINUE';



SELECT COUNT(*) FROM BRONZE.PATIENT_VISITS_RAW;
SELECT COUNT(*) FROM BRONZE.DIAGNOSIS_RAW;
SELECT COUNT(*) FROM BRONZE.BILLING_RAW;
SELECT COUNT(*) FROM BRONZE.DIM_PATIENT_RAW;
SELECT COUNT(*) FROM BRONZE.DIM_DOCTOR_RAW;



