// KPI QUERIES 

// 1. Total Visits

SELECT COUNT(*) AS TOTAL_VISITS
FROM GOLD.FACT_VISITS;

// 2. Total Revenue

SELECT SUM(TOTAL_CHARGES) AS TOTAL_REVENUE
FROM GOLD.FACT_VISITS;

// 3. Unique Patients

SELECT COUNT(DISTINCT PATIENT_ID) AS UNIQUE_PATIENTS
FROM GOLD.FACT_VISITS;


// INSIGHT QUERIES (Charts)

// 4. Revenue by Department
SELECT 
    DEPARTMENT_ID,
    SUM(TOTAL_CHARGES) AS TOTAL_REVENUE
FROM GOLD.FACT_VISITS
GROUP BY DEPARTMENT_ID
ORDER BY TOTAL_REVENUE DESC;

// 5. Revenue by Doctor
SELECT 
    DOCTOR_NAME,
    SUM(TOTAL_CHARGES) AS REVENUE
FROM GOLD.FACT_VISITS
GROUP BY DOCTOR_NAME
ORDER BY REVENUE DESC;


// 6. Visits Trend Over Time

SELECT 
    VISIT_DATE,
    COUNT(*) AS TOTAL_VISITS
FROM GOLD.FACT_VISITS
GROUP BY VISIT_DATE
ORDER BY VISIT_DATE;
