// Insert new data
INSERT INTO SILVER.PATIENT_VISITS (
    VISIT_ID, PATIENT_ID, DOCTOR_ID, DEPARTMENT_ID, VISIT_DATE, TOTAL_CHARGES
)
VALUES ('V5000', 'P006', 'D001', 'DEP01', '2024-03-30', 2000);

//CHECK STREAM
SELECT * FROM SILVER.VISIT_STREAM;


// Trigger task
EXECUTE TASK LOAD_FACT_VISITS;

//VERIFY
SELECT * FROM GOLD.FACT_VISITS;g



select * from fact_visits;
