-- Use correct schema
USE DATABASE HOSPITAL_DB;
USE SCHEMA GOLD;

-- Create FACT table (final analytics table)
CREATE OR REPLACE TABLE GOLD.FACT_VISITS AS
SELECT 
    v.VISIT_ID,
    v.PATIENT_ID,
    v.DOCTOR_ID,
    v.DEPARTMENT_ID,
    v.VISIT_DATE,
    v.TOTAL_CHARGES,
    d.DIAGNOSIS,
    b.BILL_AMOUNT,
    p.PATIENT_NAME,
    doc.DOCTOR_NAME
FROM SILVER.PATIENT_VISITS v
LEFT JOIN SILVER.DIAGNOSIS d 
    ON TRIM(v.VISIT_ID) = TRIM(d.VISIT_ID)
LEFT JOIN SILVER.BILLING b 
    ON TRIM(v.VISIT_ID) = TRIM(b.VISIT_ID)
LEFT JOIN SILVER.DIM_PATIENT p 
    ON TRIM(v.PATIENT_ID) = TRIM(p.PATIENT_ID)
LEFT JOIN SILVER.DIM_DOCTOR doc 
    ON TRIM(v.DOCTOR_ID) = TRIM(doc.DOCTOR_ID);

-- Verify output
SELECT * FROM GOLD.FACT_VISITS;


