CREATE OR REPLACE DATABASE HOSPITAL_DB;

USE DATABASE HOSPITAL_DB;

CREATE OR REPLACE SCHEMA BRONZE;
CREATE OR REPLACE SCHEMA SILVER;
CREATE OR REPLACE SCHEMA GOLD;

USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE BRONZE_STAGE;