CREATE OR REPLACE TABLE SILVER.PATIENT_VISITS AS
SELECT
    VISIT_ID,
    PATIENT_ID,
    DOCTOR_ID,
    DEPARTMENT_ID,
    TO_DATE(VISIT_DATE,'YYYY-MM-DD') AS VISIT_DATE,
    TO_NUMBER(CONSULTATION_FEE) AS CONSULTATION_FEE,
    TO_NUMBER(MEDICINE_COST) AS MEDICINE_COST,
    TO_NUMBER(LAB_COST) AS LAB_COST,
    TO_NUMBER(CONSULTATION_FEE)  + TO_NUMBER(MEDICINE_COST + TO_NUMBER(LAB_COST) AS TOTAL_CHARGES
FROM BRONZE.PATIENT_VISITS_RAW
WHERE PATIENT_ID IS NOT NULL;



CREATE OR REPLACE TABLE SILVER.DIAGNOSIS AS
SELECT 
    TRIM(VISIT_ID) AS VISIT_ID,
    TRIM(DIAGNOSIS) AS DIAGNOSIS,
    TRIM(SEVERITY) AS SEVERITY
FROM BRONZE.DIAGNOSIS_RAW
WHERE VISIT_ID IS NOT NULL;



CREATE OR REPLACE TABLE SILVER.BILLING AS
SELECT
    BILL_ID,
    VISIT_ID,
    TO_NUMBER(BILL_AMOUNT) AS BILL_AMOUNT,
    TO_DATE(BILL_DATE, 'YYYY-MM-DD') AS BILL_DATE
FROM BRONZE.BILLING_RAW;



CREATE OR REPLACE TABLE SILVER.DIM_PATIENT AS
SELECT
    PATIENT_ID,
    PATIENT_NAME,
    CITY
FROM BRONZE.DIM_PATIENT_RAW;


CREATE OR REPLACE TABLE SILVER.DIM_DOCTOR AS
SELECT
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
FROM BRONZE.DIM_DOCTOR_RAW;


// data quality check

CREATE OR REPLACE TABLE SILVER.DATA_QUALITY_REPORT AS
SELECT 
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(TRY_TO_NUMBER(BILL_AMOUNT) < 0) AS NEGATIVE_BILLING
FROM BRONZE.BILLING_RAW;

select * from data_quality_report; 

//bad patient table
CREATE OR REPLACE TABLE SILVER.BAD_PATIENT_DATA AS
SELECT
    VISIT_ID,
    PATIENT_ID,
    'Missing Patient ID' AS ERROR_REASON
FROM BRONZE.PATIENT_VISITS_RAW
WHERE PATIENT_ID IS NULL;

select * from bad_patient_data;




//VERIFY

SELECT * FROM SILVER.PATIENT_VISITS;
SELECT * FROM SILVER.BILLING;
SELECT * FROM SILVER.DIM_PATIENT;